### ISSUE TITLE
[objc] Duplicated code for equality: static `Equals` and `==`

### ISSUE THREAD

**Issue by spouliot** [mono/Embeddinator-4000#221]
```
+ (bool)equalsT1:(System_TimeSpan *)t1 t2:(System_TimeSpan *)t2;
+ (bool)equality:(System_TimeSpan *)t1 t2:(System_TimeSpan *)t2;
```

Only one should be generated. The later looks better but maybe we should model it on the instance version ?

e.g. instance

```
- (bool)isEqual:(id _Nullable)other;
```

so the static / operator version _could_ be 

```
+ (bool)areEquals:(System_TimeSpan *)t1 t2:(System_TimeSpan *)t2;
```

@VincentDondain thoughts ^

**Comment by spouliot** [comment]
note that renaming `equality` also raise questions on `inequality`

* do we rename it too ?
* do we even need to expose it ? (it's a lot of generated code to avoid a `!`)

```
+ (bool)inequality:(System_TimeSpan *)t1 t2:(System_TimeSpan *)t2;
```

**Comment by VincentDondain** [comment]
@spouliot I agree that `equality` or `equalsT1` aren't great (:

I'm ok with `areEqual` (and I think there's no **s** at the end) since it respects the naming rules.

-----

*Separate note: `isEqual` should only be called like that if the next argument's type is `id`. Otherwise you have to specify the type in the method's name like:*
```
- (BOOL)isEqualToIndexSet:(NSIndexSet *)indexSet;
```
(@spouliot new rule?).

**Comment by VincentDondain** [comment]
As for **inequality**, removing would be great otherwise maybe `areNotEqual`?

**Comment by chamons** [comment]
https://github.com/mono/Embeddinator-4000/pull/247 landed.
