### ISSUE TITLE
Add linker XML file option to objcgen driver

### ISSUE THREAD

**Issue by dalexsoto** [mono/Embeddinator-4000#301]
`decimal` support needs `decimal.ToString(System.IFormatProvider)` to not be removed by managed linker (for X.I and X.M eventually). In PR #292 I added a `linker.xml` file and gave it to mtouch as a workaround, but we need to generate this file based on the types generated and also add an option to objcgen so users can provide their [XML linker definitions](https://developer.xamarin.com/guides/cross-platform/advanced/custom_linking/) and merge them with our own.

**Comment by spouliot** [comment]
This is blocking me for #176 so I'm picking it up :)

**Comment by spouliot** [comment]
The main work was done in PR #327 

There's no need to merge the .xml files (the generated one with a user provided one) since the underlying tool (mtouch or mmp) can accept the `--xml` argument several times.

I'm also unsure if we should expose `--xml` in e4k options... there's likely a scenario that requires every mtouch/mmp option to be exposed. I think we need a more general approach that would give _extra_ arguments to clang (see #130) or other tools being called.

To avoid confusion with the work already done I'm closing this one. Another issue will be opened to track the above.
