### ISSUE TITLE
Refactoring driver.cs

### ISSUE THREAD

**Issue by chamons** [mono/Embeddinator-4000#356]
It's already 1.2k lines long. 

There are multiples classes, so division should be straightforward.

**Comment by spouliot** [comment]
This should be done with the work in master. However we need to discuss a few basic things before, including:

* master does not uses the mono source code guidelines (not sure why, it's a mono project);
* sync'ing / merges;

**Comment by tritao** [comment]
It does not use Mono guidelines because most of the codebase was started in VS in Windows so I just used its defaults, this is not a big issue it should be easy to re-format.

I've been merging the objc branch back into master every couple of weeks so it should be relatively easy to merge up to tip of objc branch.

Next week I'll check the driver code of objc branch in more detail, and send some more in depth ideas on this, but basically what I was thinking was we could have a new executable project named `Embeddinator4000.exe` with the shared driver code that links to both the ObjC and C/C++/Java backend projects (which would be DLLs).

Suggestions are welcome! :)

**Comment by chamons** [comment]
https://github.com/mono/Embeddinator-4000/blob/master/objcgen/driver.cs is a "slim" 135 lines now in master.
