### ISSUE TITLE
[Android] Way to Subclass/Callback

### ISSUE THREAD

**Issue by Zomb** [mono/Embeddinator-4000#421]
In the limitations section for Android/e4k, the documentation says that we can't subclass to callback, but the workarounds provided are for iOS. Is there any guidance on how this should be implemented on Android?
Right now, implementing an interface in java requires the __getObject() method to be implemented. Is there a type I can inherit from on the C# side to make an abstract class of sorts for me to use to callback or should I try to work around callbacks using intents?
Thank you!

**Comment by jonathanpeppers** [comment]
I need to write a test for this and see if the documentation needs updates.

Can you try inheriting from `Java.Lang.Object` and see if the Xamarin.Android generator gets you closer?

**Comment by Zomb** [comment]
Are you thinking of something like the following in a Xamarin.Android library?

```
namespace TestProjAndroid
{
    [Register("TestProjAndroid.TestClassAndroid")]
    public class TestClassAndroid : Java.Lang.Object
    {
        [Export("thisIsATestMethod")]
        public virtual string ThisIsATestMethod(string testString)
        { return string.Empty; }

        public string NormalTestMethod(string testString)
        { return testString; }
    }
}

```

This appears to result in generated code that I can't quite understand. I have tried variants of this, making the class abstract, and the method abstract etc, with out much luck!

**Comment by jonathanpeppers** [comment]
Ok, it's totally possible it doesn't work yet.

Let me research and document how to do this. We need an integration test for it at least, anyways.

**Comment by jonathanpeppers** [comment]
@Zomb I got Java interface callbacks working (after a couple changes to e4k), but it doesn't feel great due to the manual plumbing involved. Let me ask around next week and see if someone on the Xamarin.Android team has a better idea.

I see two options for callbacks on Android, which probably both need to work at some point *eventually*.

#### Java Interface
```java
//Java
public interface IJavaCallback {
    void send(String text);
}
```
```csharp
//C#
public void CallMe(IJavaCallback callback, string text)
{
    callback.Send(text);
}
```
You could also store the `IJavaCallback` instance in a variable to call later.

I got this example to work, but it had a lot of JNI machinery to hook up. Not ideal.

#### Virtual/Abstract methods

Java would just extend a virtual/abstract method declared in C#. My first attempts at getting this to work were not allowing C# to call back to Java. It appears that manual JNI code is required here, too.

#### For Now

If you need something that works now, I would recommend communicating between activities with `Intent`, `StartActivityForResult`, etc. You could also look into `BroadcastReceiver`.

**Comment by Zomb** [comment]
Sounds good! I will play around with Intents a little bit to see how well that will work. It will need some thread blocking machinery just because the parent call will be synchronous but intents are not, but it should not be too bad.
As and when you find a solution to this problem, I will try it out! :)

**Comment by jonathanpeppers** [comment]
@Zomb I have documented ways to do callbacks at the moment: https://mono.github.io/Embeddinator-4000/android-callbacks.html

If you have any ideas on this, let me know. I'm working on ways to make this better.

**Comment by Zomb** [comment]
@jonathanpeppers I have not tried this yet, but I probably will at some point in the future. I am currently using a ManualResetEvent to block the call in C#, and using LocalBroadcastManager to emulate the callback into java, and just continue when I get a response intent. As soon as I am done setting everything else up, I will come back and try this out!

**Comment by johannperez** [comment]
@jonathanpeppers android-callbacks link is broken, do you know where can I find it or something similar? Thank you!
