### ISSUE TITLE
[ObjC] objcgen for Mac says Xamarin.Mac not found...

### ISSUE THREAD

**Issue by equinox2k** [mono/Embeddinator-4000#534]
```
Parsing assemblies...
	Parsed '/Users/petertribe/Documents/Git/PNI.Mobile.Xamarin.Research/PNI.Photo.Library.Embedded/PNI.Photo.Library.Embedded.Mac/bin/Debug/PNIPhotoLibraryEmbedded.dll'
Processing assemblies...
error EM0013: Can't find the assembly 'Xamarin.Mac, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065', referenced by 'PNIMobileLibrary, Version=1.0.6513.26932, Culture=neutral, PublicKeyToken=null'.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by equinox2k** [comment]
Update: found out had to set target to macosmodern rather than macOS

**Comment by spouliot** [comment]
The supported platforms are listed in the documentation
https://mono.github.io/Embeddinator-4000/objc-platforms.html
but I'll also add the missing Mac variants to the tool's help.

Xamarin.Mac is optional (for macOS) while Xamarin.iOS is required for iOS, tvOS and watchOS (largely because of the AOT/tooling requirement).

Xamarin.Mac does not support fat applications so using any Mac platform, but `macos`, requires you to pick your ABI: either i386 or x86_64. `macos` will, by default, produce a fat output.
