### ISSUE TITLE
Unable to build a .framework using `objcgen`

### ISSUE THREAD

**Issue by alexeystrakh** [mono/Embeddinator-4000#568]
I'm trying to create a .framework for my Xamarin.iOS lib and `objcgen` can create required .h and .m files and fails to build a framework (when I add `--target=framework` param) with the following error:

> mono ./objcgen/bin/Debug/objcgen.exe iOSNativeEmbed.dll --target=framework --platform=iOS --outdir=output -c --debug

```
Compiling binding code...
Found Mono 5.4.1.7 (between 5.0.0.18 and 5.2.99)
Found Xamarin.iOS 11.6.1.3 (between 10.11.0.136 and 10.11.0.136)
    xcode-select -p
    xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7 -isysroot /Library/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT -fembed-bitcode -c output/glib.c -o output/armv7/glib.o 
clang: warning: no such sysroot directory: '/Library/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk' [-Wmissing-sysroot]
output/glib.c:29:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
```

The folder mentioned above doesn't exist (`/Library/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk`) but all the required components are installed (xcode 9, vs for mac, xamarin.ios, etc)

What could be wrong here?

**Comment by spouliot** [comment]
This looks like you do not have Xcode installed or at least set up by default. 

E.g. The `xcode-select -p` command, from your log above, returns empty. It should return something like:

```
$ xcode-select -p
/Applications/Xcode92.app/Contents/Developer
```

This makes the default, command line tools uses `/Library/Contents/Developer/` as a fallback (which does not mean it work, just that Apple tools use this to be backward compatible).

Installing Xcode is not enough - it must be run (since it can install additional components, e.g. for device support). Also once started double check the *Xcode* > *Preferences* > *Locations* that the *Command Line Tools:* points to the Xcode directory. If not then select it (it should be in the combo box).

After this doing a `xcode-select -p` inside a terminal should print out the Xcode directory and the tool should work.
