### ISSUE TITLE
iOS .framework size for simple Xamarin.iOS class-library

### ISSUE THREAD

**Issue by wcoder** [mono/Embeddinator-4000#601]
Hi everyone!

My steps:

- Create simple Xamarin.iOS class-library;
- Build as release;
- Build .framework with command:
```
objcgen \
	--gen=ObjectiveC \
	--platform=iOS \
	--target=framework \
	--outdir=$OUTPUT_PATH \
	--compile \
	--verbose \
	$PROJECT_NAME/bin/Release/$PROJECT_NAME.dll
```
- Result library size ~76Mb.

As I can suggest for Xamarin.iOS it works that:
![](https://photos-1.dropbox.com/t/2/AAAN52R1IOynmvI9eJ5aEFmd5ZUhyoQdb86GBiggXUBjaQ/12/30506652/png/32x32/3/1519146000/0/2/1.png/EJXXgRcYo4hcIAcoBw/x2a6Jo7LkZ3fN15AHjPcJuF17AS7IF9y-ZFyZpQBLmI?dl=0&preserve_transparency=1&size=2048x1536&size_mode=3)

What you recommend me for reducing this size?

What about to setup linker?

**Comment by spouliot** [comment]
@wcoder your link to an image? (or something else) is broken.

Anyhow the linker is *already* enabled. You can look at the size of the .dll inside the framework and you'll see they are much smaller than the ones from shipping with Xamarin.iOS.

So why is this still so big ? 

Because when building an iOS framework you get slices for
* armv7
* armv7s
* arm64
* i386
* x86_64

for all native code, including:
* the mono runtime (libmono);
* the Xamarin.IOS runtime;
* the AOT'ed **and linked** BCL;
* the e4k generated binding code;

and you need the shared managed code, i.e. all the .dll (stripped of IL since it's AOT'ed).

When I build the `UnitsNet.dll` project, under `samples/UnitsNet`, as an iOS release framework it's _only_ 49.4 MB on disk. Your 76MB is likely because your project is bigger or requires a lot more of the BCL to be useful.

While the numbers might seem big keep in mind that using this in your own project will cut down the non required architectures. So if you build an fat application for arm7 and arm64 then most of the framework will be stripped (2/5 of the native code + the managed .dll).

So it's big because it covers everything, which makes it easy to use immediately in any situation. It's up to the final toolchain (Xcode in this case) to trim the non-required code.
