### ISSUE TITLE
libmonosgen-2.0.so: unauthorized access to "/system/lib/libsqlite.so"

### ISSUE THREAD

**Issue by fallenstardust** [mono/Embeddinator-4000#673]
now i implemented the aar and try to onCreate it through Android but while i run it on my Android mobile and it cannot onCreate successfully and shows me a log：

Detected problems with app native libraries
(please consult log for detail):
libmonosgen-2.0.so: unauthorized access to "/system/lib/libsqlite.so"

do you know how to fix it?

**Comment by emysa341** [comment]
Try to update all sqlite nuget packages within the Manage Nuget Package section.

**Comment by mercury233** [comment]
The project @fallenstardust talking about is https://github.com/mercury233/libWindbot , I'm using Mono.Data.Sqlite.dll, not from nuget.

This issue is said to be fixed in Xamarin.Android_6.0.4
https://developer.xamarin.com/releases/android/xamarin.android_6/xamarin.android_6.0/#Xamarin.Android_6.0.4

And the same way to use sqlite works on a normal xamarin app (https://github.com/mercury233/WindBotMobile).

**Comment by mercury233** [comment]
I guess I found the reason. `Mono.Data.Sqlite.dll.config` is compressed in the apk. 
Embeddinator-4000 need `aaptOptions { noCompress 'dll' }` but the config file should also be prevented from compressed.
After using `aaptOptions { noCompress 'dll', 'config' }` this issue never appear again.

**Comment by fallenstardust** [comment]
thank you！
