### ISSUE TITLE
Use more than one embedded library in a project:  .NET Limitation

### ISSUE THREAD

**Issue by amitkhoth** [mono/Embeddinator-4000#750]
I have two Queries For Embeddinator-4k

**Query 1:** 

**First is For Android Native App:**

I Have an existing android Application project(Java)  in which I have separate Plugin for Different Module.
Ex. I have a android application which support Multiple Plugin.(Plugin are downloaded from internet after the app is installed on device)
Main Application -> Plugin1, Plugin2, Plugin3 etc.

For Each Plugin Module I want to use separate .AAR  create from Embeddinator tool.
**Can I use multiple .AAR for multiple plugin of same Application?**

If  not , What is reason behind this?
           or 
is there any Future Planning for the same?

**Query 2:
 iOS App:**

I have one workspace in Xcode in which I have Multiple Project for separate Module.

I want to use .Framework created from Embeddinator Tool .
**Can I use multiple .Framework for Separate project of same Workspace?**
  
if yes , How i can achieve this?
if Not, why is this Limitation ?
  or
 any Future Planning for the same?

**Bitcode Limitation:**
Currently .NET Embedding does not support bitcode on iOS, which is enabled for some Xcode project templates. This will have to be disabled to successfully link generated frameworks.

Why is this Limitation?
Please expalin.

**Comment by whitneyschmidt** [comment]
@amitkhoth Thank you for your feedback! The MS docs for E4K are a great reference for these types of questions: https://docs.microsoft.com/en-us/xamarin/tools/dotnet-embedding/

1 & 2:

You can use more than one embedded library in a project. You can use the generator to create a single library that includes several assemblies (from different projects).

The issue is that each embedded library contains its own mono runtime, and a project cannot have two mono runtimes. Building several assemblies into the same library results in only one mono runtime.

There's a bit more information on this here: https://docs.microsoft.com/en-us/xamarin/tools/dotnet-embedding/limitations

Bitcode:

E4K cannot support bitcode because Xamarin.iOS does not support it. We don't support bitcode in Xamarin.iOS for a couple of reasons:

a) Generating bitcode makes binaries larger, and leads to longer builds.
b) There is not a major benefit to generating bitcode. Apple would be able to recompile generated bitcode, but not optimize or modify it.
