### ISSUE TITLE
objcgen/make  gets "0 Errors" but also "No shellcheck tool found"

### ISSUE THREAD

**Issue by dbell-movano** [mono/Embeddinator-4000#768]
### Steps to Reproduce

1. git clone https://github.com/mono/Embeddinator-4000.git
2. cd Embeddinator-4000
3. git submodule update --recursive --init
4. cd objcgen
5. make

### Actual Behavior

"No shellcheck tool found"

AND IS THE DIRECTORY...

.gitignore
CachedValue.cs
EqualsHelper.cs
ErrorHelper.cs
HashHelper.cs
Internals.md
Logger.cs
Make.config
Make.config.inc
Makefile
NameGenerator.cs
README.md
TypeMapper.cs
Version.generated.cs
bin
classhelper.cs
comparablehelper.cs
driver.cs
embedder.cs
error.cs
extensions.cs
generate-version.sh
generator.cs
methodhelper.cs
obj
objcgen.csproj
objcgenerator-helpers.cs
objcgenerator-postprocessor.cs
objcgenerator-processor.cs
objcgenerator-subscripts.cs
objcgenerator.cs
objcprocessor.cs
operatoroverloads.cs
packages.config
processedtypes.cs
processor.cs
protocolhelper.cs
script
sourcewriter.cs
system-check.cs
system-dependencies.sh
thin-framework.sh
utils.cs

### Environment
macOS 10.14.6

``` macOS 10.14.6man 
```

**Comment by chamons** [comment]
Creating multiple new issues for your troubles in building the project will not get you assistance more quickly. Trouble building an open source project is more appropriate through a gitter such as https://gitter.im/xamarin/xamarin-macios for example.

In any case, as I noted before "No shellcheck tool found" is a warning, and can be ignored. We just skipped part of the build that does shell checks on our scripts, since you don't have it installed.

It looks like you need to run `make nuget-prep` to create a _build directory that I mentioned before.

I'll repeat a question I asked before, why are you trying to build this instead of using a nuget version?

**Comment by chamons** [comment]
Discussion continues in duplicate https://github.com/mono/Embeddinator-4000/issues/764
